excluded:
  - .build
  - External
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - first_where
  - implicit_return
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_nimble
  - prohibited_super_call
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
line_length:
  warning: 200
  error: 300
